# Generated by Django 3.1.7 on 2021-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Уникальный код валюты')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Курс по отношению к рублю')),
            ],
        ),
    ]
